db:
  host: 'mysql.clarksonmsda.org'
  user: 'ia637'
  passwd: 'ia637clarkson'
  db: 'ia637'
  port: 3306
tables:
  shelter: 'VB_Shelters'
  user: 'VB_Users'
  pet: 'VB_Pets'
  adoption: 'VB_Adoptions'
  appointment: 'VB_Appointments'

